name: "Rails CI"
on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
    
jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:password@localhost:5432/rails_test
    
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: rails_test
          POSTGRES_PASSWORD: password
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.3"
          bundler-cache: true
          working-directory: backend
          
      - name: Set up database schema
        working-directory: backend
        run: |
          bin/rails db:create
          bin/rails db:schema:load
          
      - name: Run RSpec tests
        working-directory: backend
        run: bundle exec rspec
  
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.3"
          bundler-cache: true
          working-directory: backend

      - name: Lint code with RuboCop
        working-directory: backend
        run: bundle exec rubocop -f github